### ISSUE TITLE
New Module: MitoHiFi

### ISSUE THREAD

**Issue by mahesh-panchal** [NBISweden/Earth-Biogenome-Project-pilot#29]
**Which tool should be included?**

https://github.com/marcelauliano/MitoHiFi

**How is it used?**

```bash
singularity exec \
    --bind /path/on/disk/to/data/:/data/ \
    /path/to/mitohifi-v2.2.sif  \
        mitohifi.py \
            -r "/data/f1.fasta /data/f2.fasta /data/f3.fasta" \
            -f /data/reference.fasta \
            -g /data/reference.gb  \
            -t 10 \
            -o 2 
```

**Which workflow should it be included in?**

Organelle assembly workflow

**Comment by verku** [comment]
MitoHiFi can be run in two modes: from contigs (-c) or from reads (-r). Currently, it is implemented to run from contigs, as this allows for a special plant genome parameter. We discussed to implement the other mode (from reads) as well to be able to test which works better.

**Comment by mahesh-panchal** [comment]
https://github.com/nf-core/modules/tree/master/modules/nf-core/mitohifi

```
nf-core modules install mitohifi/mitohifi
nf-core modules install mitohifi/findmitoreference
```
