### ISSUE TITLE
New Module: OMArk

### ISSUE THREAD

**Issue by gbdias** [NBISweden/Earth-Biogenome-Project-pilot#54]
**Which tool should be included?**
OMArk. 
https://github.com/DessimozLab/OMArk

**How is it used?**
```shell
# installation
pip install omark
# download full database
wget https://omabrowser.org/All/LUCA.h5
# run search and benchmark
omamer search --db LUCA.h5 --query my_proteome.fa --out my_proteome.omamer --nthreads 10
omark -f my_proteome.omamer -d LUCA.h5 -o results
```

**Which workflow should it be included in?**
Quality control.

**Comment by gbdias** [comment]
Closing since I realised this might not be needed for the EBP workflow as it is geared towards annotation evaluation rather than assembly evaluation.

**Comment by mahesh-panchal** [comment]
You can add it as an issue here: https://github.com/NBISweden/pipelines-nextflow
Just say if it needs to be a workflow of it's own. Check the Mermaid diagram.
