### ISSUE TITLE
Test data - Drosophila melanogaster

### ISSUE THREAD

**Issue by gbdias** [NBISweden/Earth-Biogenome-Project-pilot#95]
- _Drosophila melanogaster_ is an interesting subject for test data since 
  - the genome is small (±180Mb)
  - there are only 4 chromosomes (can expect 6 chromosome arms after scaffolding because the centromeres are hard to go through even with Hi-C)
  - plenty of sequencing data is available
- There is good PacBio HiFi data from the F1 of a cross between two highly inbred strains (A4 and ISO1).
- This should be a good heterozygous genome that assembles very well with hifiasm. I am currently testing the assembly to make sure. Will post results to this thread.
- There is Hi-C data for other strains, need to test if it works well.

**Comment by gbdias** [comment]
## HiFi data
- https://ncbi.nlm.nih.gov/sra/SRX6957826[accn]
- This data was generated by PacBio for demonstrating Sequel and HiFi.
- It has an excellent read size (size selected to 24kb).
- The full dataset is 25.8 Gbp which corresponds to ~143x theoretical haploid coverage.
- I was able to subsample 10% of the reads and still get a reasonable assembly in 13 minutes using hifiasm with 20cpus.
- Phasing is probably not great at this coverage but the haplotypes are similar enough that the final primary assembly is still very contiguous.

> x-axis D.mel reference, y-axis hifiasm

![SRR10238607_0 1 paf](https://github.com/NBISweden/Earth-Biogenome-Project-pilot/assets/7614153/84780db0-9e07-45eb-99ba-b4ee81f966b6)

**Comment by MartinPippel** [comment]
Is the subsampled data set already publicly available somewhere?
